### ISSUE TITLE
no work on lenovo flex 5i

### ISSUE THREAD

**Issue by kvkwww** [WeirdTreeThing/chromebook-linux-audio#241]
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Unknown/Unsupported chromebook model: taeko4es

taeko4es=taeko
The 4es suffix means factory beta.
There's no difference except the cpu is beta.

**Comment by WeirdTreeThing** [comment]
It should work now

**Comment by koluckirafal** [comment]
@kvkwww Does the issue still persist after re-running the script?
